fcstudy-project/FastTime-backend

src/main/java/com/fasttime/domain/comment/controller/CommentController.java, src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java, src/main/java/com/fasttime/domain/comment/controller/CommentRestControllerAdvice.java, src/main/java/com/fasttime/domain/comment/dto/CommentDto.java, src/main/java/com/fasttime/domain/comment/dto/request/CreateCommentRequest.java, src/main/java/com/fasttime/domain/comment/dto/request/DeleteCommentRequest.java, src/main/java/com/fasttime/domain/comment/dto/request/UpdateCommentRequest.java, src/main/java/com/fasttime/domain/comment/entity/Comment.java, src/main/java/com/fasttime/domain/comment/exception/NotFoundException.java, src/main/java/com/fasttime/domain/comment/repository/CommentRepository.java, src/main/java/com/fasttime/domain/comment/service/CommentService.java, src/test/java/com/fasttime/domain/comment/controller/CommentRestControllerTest.java, src/test/java/com/fasttime/domain/comment/entity/CommentTest.java, src/test/java/com/fasttime/domain/comment/service/CommentServiceTest.java
- 게시글에 비익명, 익명으로 댓글을 등록할 수 있다. 
- 댓글에 비익명, 익명으로 대댓글을 등록할 수 있다. 
- 댓글 내용을 수정할 수 있다. 
- 댓글을 삭제(SOFT DELETE)할 수 있다. 
- 댓글 ID를 이용해 댓글 정보를 조회할 수 있다. 
- 등록, 수정, 삭제 요청에 대해 Validation 검증이 이뤄진다. 
- 엔터티, 서비스, 컨트롤러 각 기능을 테스트 코드를 통해 테스트할 수 있다. 
---
- 게시글과 회원 정보를 불러오는 작업은 해당하는 각 도메인 서비스에 구현된 기능을 사용하도록 수정할 계획입니다. 
- 회원 정보 조회 시 엔터티에 맞게 Long 자료형을 사용하도록 MemberRepository 수정이 필요할 것 같습니다. @ghrltjdtprbs 확인 부탁드립니다.
=> 댓글 등록, 수정, 삭제 기능 구현

src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java, src/main/java/com/fasttime/domain/comment/controller/CommentRestControllerAdvice.java, src/test/java/com/fasttime/domain/comment/controller/CommentRestControllerTest.java
- 댓글 REST Controller에서 응답 시 ResponseDTO를 사용하도록 수정했습니다. 
- 이에 따라 에러 메시지 또한 ```message```에 담겨 보내지기 때문에 댓글 컨트롤러 테스트 코드를 수정했습니다.
=> 댓글 컨트롤러에서 ResponseDTO를 사용하도록 수정

src/main/java/com/fasttime/domain/comment/controller/CommentRestControllerAdvice.java, src/main/java/com/fasttime/domain/comment/exception/CommentNotFoundException.java, src/main/java/com/fasttime/domain/comment/exception/NotFoundException.java, src/main/java/com/fasttime/domain/comment/service/CommentService.java, src/main/java/com/fasttime/domain/member/controller/MemberControllerAdvice.java, src/main/java/com/fasttime/domain/member/exception/UserNotFoundException.java, src/main/java/com/fasttime/domain/post/exception/NotPostWriterException.java, src/main/java/com/fasttime/domain/post/exception/PostNotFoundException.java, src/main/java/com/fasttime/domain/post/service/PostCommandService.java, src/main/java/com/fasttime/global/exception/ApplicationException.java, src/main/java/com/fasttime/global/exception/GlobalExceptionRestAdvice.java, src/main/java/com/fasttime/global/util/ResponseDTO.java, src/test/java/com/fasttime/domain/comment/service/CommentServiceTest.java, src/test/java/com/fasttime/domain/member/controller/MemberControllerTestForAuto.java
* Application 전용 Exception 계층화
* GlobalExceptionAdvice 생성
```java
public class PostNotFoundException extends ApplicationException {
private static final HttpStatus httpStatus = HttpStatus.NOT_FOUND;
public PostNotFoundException() {
super(httpStatus, "존재하지 않는 게시글입니다.");
}
}
``` 
* ApplicationException을 상속한 예외들은 아래의 Advice에서 처리됩니다.
* 예외 생성 시 해당 도메인에 관련 예외를 생성한 후 사용하세요.
* 기존의 예외들은 모두 변경을 실시했습니다.
<br>
```java
@Slf4j
@RestControllerAdvice
public class GlobalExceptionRestAdvice {
@ExceptionHandler
public ResponseEntity<ResponseDTO<Object>> applicationException(ApplicationException e) {
log.error("applicationException: " + e.getMessage());
return ResponseEntity
.status(e.getHttpStatus())
.body(ResponseDTO.res(e.getHttpStatus(), e.getMessage()));
}
@ExceptionHandler
public …
```
=> 예외처리를 리팩토링 한다.

src/main/java/com/fasttime/domain/comment/repository/CommentRepository.java, src/main/java/com/fasttime/domain/comment/service/CommentService.java, src/test/java/com/fasttime/domain/comment/service/CommentServiceTest.java
- 컨트롤러 어드바이스 수정
- Post로 해당 게시글에 달린 댓글을 조회할 수 있는 기능 추가
- Member로 해당 회원이 작성한 댓글을 조회할 수 있는 기능 추가
=> 댓글 조회 기능 추가 구현

src/main/java/com/fasttime/domain/post/controller/PostController.java, src/main/java/com/fasttime/domain/post/dto/service/request/PostCreateServiceDto.java, src/main/java/com/fasttime/domain/post/dto/service/response/PostDetailResponseDto.java, src/main/java/com/fasttime/domain/post/dto/service/response/PostsResponseDto.java, src/main/java/com/fasttime/domain/post/service/PostQueryService.java, src/test/java/com/fasttime/domain/post/unit/controller/PostControllerTest.java, src/test/java/com/fasttime/domain/post/unit/service/PostQueryServiceTest.java, src/test/java/com/fasttime/util/ControllerUnitTestSupporter.java
Motivation:
- 이제 Template-Engine이 아닌 Frontend 서버를 따로 운용하기 떄문에 Rest-API 로 전환합니다.
Modification:
- `Controller` -> `RestController` 으로 전환
- 테스트 코드 수정
=> [refactor] 게시글 API 들을 rest로 전환

src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java, src/main/java/com/fasttime/domain/comment/service/CommentService.java, src/test/java/com/fasttime/domain/comment/controller/CommentRestControllerTest.java, src/test/java/com/fasttime/domain/comment/service/CommentServiceTest.java
게시글에서 댓글을 조회할 수 있도록 API를 추가 구현했습니다. 
- 추가할 기능 TEST 작성
- 게시글 ID로 댓글 조회 기능 추가
- 게시글에서  댓글 API 추가
- 댓글 API 메서드 변경 (DELETE, PATCH 사용)
- 추가한 API TEST 작성
- 메서드명 리팩토링
=> [feat] 게시글 댓글 조회 API 구현

src/docs/asciidoc/comment/comment-api.adoc, src/docs/asciidoc/post/post-api.adoc, src/test/java/com/fasttime/domain/comment/docs/CommentControllerDocsTest.java, src/test/java/com/fasttime/domain/comment/unit/controller/CommentRestControllerTest.java, src/test/java/com/fasttime/domain/comment/unit/entity/CommentTest.java, src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java
Spring REST Docs를 사용하여 댓글 API 문서를 만들었습니다. 
- Spring REST Docs를 위해 CommentControllerDocsTest 작성
- 댓글 API .adoc 작성
=> [feat] 댓글 Spring REST Docs 도입

src/main/java/com/fasttime/global/config/WebConfig.java
Motivation:
- 잘못된 @Profile 설정으로 인해 몇몇 실행 Profile 에서 WebConfig 설정이 작동하지 않는 것을 발견했습니다.
- 위 문제를 해결하기 위해 우선적으로 @Profile 을 제거하기로 결정했습니다.
Modification:
- `WebConfig.class`의 `@Profile` 제거
=> [fix] WebConfig Profile 삭제

src/docs/asciidoc/report/report-api.adoc, src/main/java/com/fasttime/domain/report/contoller/ReportRestController.java, src/test/java/com/fasttime/domain/comment/docs/CommentControllerDocsTest.java, src/test/java/com/fasttime/domain/report/docs/ReportControllerDocsTest.java, src/test/java/com/fasttime/domain/report/unit/controller/ReportRestControllerTest.java, src/test/java/com/fasttime/domain/report/unit/entity/ReportTest.java, src/test/java/com/fasttime/domain/report/unit/service/ReportServiceTest.java
Spring REST Docs를 사용하여 신고 API 문서를 만들었습니다. 
- Spring REST Docs를 위해 ReportControllerDocsTest 작성
- 신고 API .adoc 작성
=> [feat] 신고 Spring API Docs 도입

src/docs/asciidoc/member/member-api.adoc, src/main/java/com/fasttime/domain/member/controller/EmailController.java, src/main/java/com/fasttime/domain/member/controller/MemberController.java, src/main/java/com/fasttime/domain/member/dto/MemberDto.java, src/main/java/com/fasttime/domain/member/request/EditRequest.java, src/main/java/com/fasttime/domain/member/response/EditResponse.java, src/main/java/com/fasttime/domain/member/service/MemberService.java, src/test/java/com/fasttime/domain/member/controller/EmailControllerTest.java, src/test/java/com/fasttime/domain/member/controller/MemberControllerTest.java, src/test/java/com/fasttime/domain/member/docs/MemberControllerDocsTest.java
**Member Spring Rest Docs 도입**
- Spring REST Docs를 위해 MemberControllerDocsTest 작성
- 회원가입, 회원탈퇴, 회원정보 수정, 회원정보 조회 적용
- 회원정보 수정, 마이페이지 누락된 응답필드 추가 
**회원정보 조회 기능 구현**
- 현재 로그인 된 사용자의 이메일, 닉네임, 프로필사진url을 조회한다.
- 리펙토링 예정입니다.
**회원정보 수정, 회원정보 조회, 회원탈퇴 리펙토링**
- postman으로 테스트한 결과 작동하지 않아 수정했습니다.
**url 통일**
- email,member controller의 url 을 /api/v1/으로 통일했습니다.
------
* 작동하지 않는 기능 수정하느라 급하게 만들었으니 감안하고 봐주세요. 후에 리펙토링 예정입니다.
=> 회원정보 조회 및 Member Spring Rest Docs 도입

src/docs/asciidoc/index.adoc, src/docs/asciidoc/record/record-api.adoc, src/main/java/com/fasttime/domain/record/controller/RecordRestController.java, src/main/java/com/fasttime/domain/record/controller/RecordRestControllerAdvice.java, src/main/java/com/fasttime/domain/record/dto/RecordDTO.java, src/main/java/com/fasttime/domain/record/dto/request/CreateRecordRequestDTO.java, src/main/java/com/fasttime/domain/record/dto/request/DeleteRecordRequestDTO.java, src/main/java/com/fasttime/domain/record/entity/Record.java, src/main/java/com/fasttime/domain/record/exception/DuplicateRecordException.java, src/main/java/com/fasttime/domain/record/exception/RecordNotFoundException.java, src/main/java/com/fasttime/domain/record/service/RecordService.java, src/test/java/com/fasttime/domain/record/docs/RecordControllerDocsTest.java, src/test/java/com/fasttime/domain/record/unit/controller/RecordRestControllerTest.java, src/test/java/com/fasttime/domain/record/unit/entity/RecordTest.java, src/test/java/com/fasttime/domain/record/unit/service/RecordServiceTest.java
- 게시글 좋아요/싫어요 등록 기능 구현
- 회원이 해당 게시글에 대해 등록한 좋아요/싫어요 조회 기능 구현
- 게시글 좋아요/싫어요 취소 기능 구현
- 좋아요/싫어요 등록 혹은 취소 시 게시글의 likeCount, hateCount 증감
- 게시글 엔터티의 likeCount, hateCount 값을 변경할 수 있는 메서드가 부재하여 일단 보류해뒀습니다. 
- 해당 기능을 게시글 담당 자현님이 구현해주시거나, 제가 추가하여 곧 수정할 예정입니다.
=> [feat] 게시글 좋아요/싫어요 API 구현

src/main/java/com/fasttime/domain/record/repository/RecordRepository.java, src/main/java/com/fasttime/domain/record/service/RecordService.java, src/test/java/com/fasttime/domain/record/unit/service/RecordServiceTest.java
- 게시글 좋아요/싫어요 등록 시 게시글 엔터티 필드를 건드리기 때문에 updateAt이 계속 갱신됨. 
- 게시글 수정이 아닌데 updateAt이 갱신되면 안됨. 
- 게시글 좋아요/싫어요 합계 수정하는 로직 제거
- postId에 대한 좋아요/싫어요 개수 반환하는 메서드 추가
=> [feat] 게시글 좋아요/싫어요 조회 기능 추가

src/docs/asciidoc/record/record-api.adoc, src/main/java/com/fasttime/domain/record/controller/RecordRestController.java, src/main/java/com/fasttime/domain/record/controller/RecordRestControllerAdvice.java, src/main/java/com/fasttime/domain/record/dto/request/CreateRecordRequestDTO.java, src/main/java/com/fasttime/domain/record/dto/request/DeleteRecordRequestDTO.java, src/main/java/com/fasttime/domain/record/exception/AlreadyExistsRecordException.java, src/main/java/com/fasttime/domain/record/exception/DuplicateRecordException.java, src/main/java/com/fasttime/domain/record/repository/RecordRepository.java, src/main/java/com/fasttime/domain/record/service/RecordService.java, src/test/java/com/fasttime/domain/record/docs/RecordControllerDocsTest.java, src/test/java/com/fasttime/domain/record/unit/controller/RecordRestControllerTest.java, src/test/java/com/fasttime/domain/record/unit/service/RecordServiceTest.java
- 세션 사용으로 인한 좋아요/싫어요 API 수정
- 좋아요/싫어요 등록, 조회, 삭제 시 memberId를 필드가 아닌 세션에서 가져옴
- 좋아요/싫어요 등록 API url 수정
- 좋아요/싫어요 등록 요청 필드로 isLike 추가
- 좋아요/싫어요 익셉션 추가
- 좋아요/싫어요 Service, Controller, Repository  리팩토링
- 좋아요/싫어요 테스트 코드 수정
- 좋아요/싫어요 REST Docs 수정
=> [refactor] 좋아요/싫어요 기능 리팩토링

src/docs/asciidoc/comment/comment-api.adoc, src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java, src/main/java/com/fasttime/domain/comment/dto/request/CreateCommentRequestDTO.java, src/main/java/com/fasttime/domain/comment/dto/request/DeleteCommentRequestDTO.java, src/main/java/com/fasttime/domain/comment/dto/request/UpdateCommentRequestDTO.java, src/main/java/com/fasttime/domain/comment/service/CommentService.java, src/test/java/com/fasttime/domain/comment/docs/CommentControllerDocsTest.java, src/test/java/com/fasttime/domain/comment/unit/controller/CommentRestControllerTest.java, src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java
- 댓글 API 수정
- 댓글 등록, 마이페이지 조회 시 memberId를 필드나 파라미터가 아닌 세션에서 가져옴
- 댓글 등록, 삭제 시 댓글 DTO를 응답하지 않도록 수정
- 댓글 Service, Controller  리팩토링
- 댓글 테스트 코드 수정
- 댓글 REST Docs 수정
=> [refactor] 댓글 기능 리팩토링

src/main/java/com/fasttime/global/exception/GlobalExceptionRestAdvice.java
Motivation:
- spring 에서는 checked exception인 `SQLException`를 unchecked exception `DataAccessException` 으로 변환하는 기술을 제공합니다. ExceptionHandler 에서 해당 방식을 추가합니다.
- `serverException` 에서 `BAD_REQUEST`를 httpStatus로 전달하는 것을 확인했습니다. 이를 `INTERNAL_SERVER_ERROR` 로 변경하고자 합니다.
Modification:
- `DataAccessException` handling 추가
- `serverException` 에서 `BAD_REQUEST` 를 던지던 것을 `INTERNAL_SERVER_ERROR`로 변경
=> [refactor] 익셉션 핸들링 분기처리

src/main/java/com/fasttime/domain/post/entity/Post.java, src/main/java/com/fasttime/domain/post/service/PostCommandService.java, src/main/java/com/fasttime/domain/post/service/PostCommandUseCase.java, src/main/java/com/fasttime/domain/record/service/RecordService.java, src/test/java/com/fasttime/domain/record/unit/service/RecordServiceTest.java
Motivation:
- 1차적으로 RecordService 에서 post의 likeCount를 수정할 수 있게끔 추가했습니다.
Modification:
- `likeOrHate` 로직 추가
=> [fix] likeCount 누락 수정

src/main/java/com/fasttime/domain/post/repository/PostRepositoryImpl.java, src/main/java/com/fasttime/domain/post/service/PostQueryService.java
Motivation:
- 전체 쿼리를 수행한 후 `deletedAt is not null` 을 필터링하다 보니, 요청된 pageSize에 맞게 반환하지 못하는 현상을 발견했습니다.
Modification:
- 쿼리를 할 때 `deletedAt is not null` 조건을 사용하기로 변경했습니다.
=> [feature] 삭제된 게시글을 쿼리하지 않는다.

src/main/java/com/fasttime/domain/member/controller/AdminController.java, src/main/java/com/fasttime/domain/member/controller/MemberController.java, src/main/java/com/fasttime/domain/member/service/AdminService.java, src/main/java/com/fasttime/domain/member/service/MemberService.java
- ControllerAdvice에서 bindException를 처리하고 있으므로, 기존 코드에 있던 BindingResult를 삭제하였습니다.
- AdminService에서 orElseThrow() 메소드를 활용하여, 예외를 발생시키는 코드를 압축하였습니다.
- MemberService에서 불필요한 Else문을 삭제하였습니다.
- 로그인 시, 논리 삭제된 멤버는 로그인을 하지 못하도록 수정하였습니다.
=> [refactor] BindingResult 삭제 및 orElseThrow() 사용

src/main/java/com/fasttime/global/config/WebConfig.java
Motivation:
- 좋아요/싫어요 및 신고 API가 login interceptor의 `PathPattern`에 누락되어 로그인 관련 분기처리가 제대로 되지 않는 문제가 발생했습니다. 이를 해결하기 위해 댓글 API 경로를`PathPattern`를 추가했습니다.
Modification:
- `WebConfig.java`에서 LoginInterceptor addPathPatterns() 에 report, record api 경로 추가
=> [fix] 누락된 login interceptor `PathPattern` 추가

src/main/java/com/fasttime/domain/post/entity/Post.java, src/main/java/com/fasttime/domain/post/repository/PostRepositoryCustom.java, src/main/java/com/fasttime/domain/post/repository/PostRepositoryImpl.java, src/main/java/com/fasttime/domain/post/service/PostQueryService.java
Motivation:
- 게시글 목록에서 댓글 갯수를 가져올 수 있도록 쿼리를 추가합니다.
Modification:
- `Post` entity 에서 `List<Comment>` 연관관계 추가
- 댓글 수를 가져오는 querydsl 코드 추가.
- `PostsResponseDto` 에서 `commentCount` 추가
=> [feature] 게시글 댓글 갯수 쿼리 기능 추가

src/main/java/com/fasttime/domain/post/controller/PostController.java, src/main/java/com/fasttime/domain/post/dto/controller/request/PostCreateRequestDto.java, src/test/java/com/fasttime/domain/post/docs/PostControllerDocsTest.java, src/test/java/com/fasttime/domain/post/unit/controller/PostControllerTest.java
Motivation:
- 로그인 보안성을 높이기 위해 RequestBody 에서 memberId를 받는 것을 HttpSession으로부터 받기로 변경했습니다.
Modification:
- `memberId` 제거 from `RequestBody`
- `memberId` 생성 to `HttpSession`
=> [refacor] 게시글 API `HttpSession` 사용

src/docs/asciidoc/member/member-api.adoc, src/main/java/com/fasttime/domain/member/controller/MemberController.java, src/main/java/com/fasttime/domain/member/entity/Member.java, src/main/java/com/fasttime/domain/member/repository/MemberRepository.java, src/main/java/com/fasttime/domain/member/service/MemberService.java, src/main/java/com/fasttime/domain/member/service/ScheduledTasks.java, src/main/java/com/fasttime/global/config/SchedulingConfig.java, src/main/resources/application.yaml, src/test/java/com/fasttime/domain/member/controller/MemberControllerTest.java, src/test/java/com/fasttime/domain/member/docs/MemberControllerDocsTest.java, src/test/java/com/fasttime/domain/member/unit/service/AdminServiceTest.java
- 회원 탈퇴 시 유효 기간을 1년으로 설정하고, 유효 기간이 지나면 db에서 자동 삭제 기능 추가
- 탈퇴 유효 기간이 지나지 않은 계정(동일 이메일)으로 재가입 시 기존 계정 복구 기능 추가
- join 리팩토링
- 계정 복구 Spring API Docs 추가
- MemberControllerTest 코드 수정
=> [feat] 탈퇴 계정 유효기간 설정 및 계정 복구 추가

src/main/java/com/fasttime/domain/article/entity/Article.java, src/main/java/com/fasttime/domain/article/entity/ReportStatus.java, src/main/java/com/fasttime/domain/article/exception/BadArticleReportStatusException.java, src/main/java/com/fasttime/domain/member/service/AdminService.java, src/main/java/com/fasttime/domain/report/service/ReportService.java, src/main/java/com/fasttime/global/exception/ErrorCode.java, src/test/java/com/fasttime/domain/article/unit/entity/PostTest.java, src/test/java/com/fasttime/domain/article/unit/repository/ArticleRepositoryTest.java, src/test/java/com/fasttime/domain/member/unit/controller/AdminControllerTest.java, src/test/java/com/fasttime/domain/member/unit/service/AdminServiceTest.java, src/test/java/com/fasttime/domain/report/unit/service/ReportServiceTest.java
Motivation:
- Enum ReportStatus 의 naming 들이 다소 모호함을 가지고 있었습니다. 이를 개선하기 위해서 enum class의 type 들을 더 세분화했고, 이름을 재설정하였습니다.
Modification:
- `REPORTED` -> `WAIT_FOR_REPORT_REVIEW`
- `REPORT_ACCEPT` 추가
=> [refactor] `ReportStatus` Renaming

src/main/java/com/fasttime/domain/article/service/ArticleReportService.java, src/main/java/com/fasttime/domain/article/service/usecase/ArticleReportUseCase.java, src/test/java/com/fasttime/domain/article/unit/service/ArticleReportServiceTest.java
Motivation:
- 현재 `AdminService` 에서 게시글 신고를 담당하고 있습니다. 문제는 `AdminService` 에서 엔티티를 직접 조회 및 수정을 하고 있다는 것인데, 이는 `AdminService`가 `Article`에 대한 강한 의존성을 갖게 되는 문제점을 낳게 됩니다. 이를 해결하기 위해서 `ArticleService` 측에서 신고 관련 API를 제공하는것이 더 타당하게 여겨집니다.
Modification:
- `ArticleReportUseCase`, `ArticleReportService` 추가
- 테스트 코드 추가
=> [refactor] 게시글 신고 기능 추출

src/main/java/com/fasttime/domain/article/service/ArticleSettingProvider.java
Motivation:
- 현재 매직넘버를 해당 서비스의 `private static final` 으로 제공하고 있습니다. 하지만, 여러 클래스에서 같은 매직넘버가 필요해짐에 따라 Utils 클래스가 필요하게 되었습니다.
- 유틸클래스를 제공하는 것은 좋지만, 이는 객체지향의 관점에서 여러 클래스간의 강한 의존성을 만들 수 있습니다. 이를 해결하기 위해서 스프링의 주입방식을 채택하게 되었습니다.
Modification:
- `ArticleSettingProvider` 생성
=> [feat] 외부 주입 프로퍼티 Provider 제공

src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java, src/main/java/com/fasttime/domain/comment/controller/CommentRestControllerAdvice.java, src/main/java/com/fasttime/domain/comment/exception/NotCommentAuthorException.java, src/main/java/com/fasttime/domain/comment/service/CommentService.java, src/main/java/com/fasttime/global/exception/ErrorCode.java, src/test/java/com/fasttime/domain/comment/docs/CommentControllerDocsTest.java, src/test/java/com/fasttime/domain/comment/unit/controller/CommentRestControllerTest.java, src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java
- 댓글 작성자가 아니어도 댓글 ID를 통해 댓글을 수정하거나 삭제할 수 있다. 
- 댓글 수정 및 삭제 요청 회원이 댓글 작성자인지 검증 로직이 부재하다. 
- 댓글 수정 및 삭제 시 댓글 작성자가 맞는지 확인한다. 
- 일치하지 않으면 수정 삭제 불가하다.
=> 댓글 작성자만 댓글 수정 삭제할 수 있도록 수정

src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java, src/main/java/com/fasttime/domain/comment/controller/CommentRestControllerAdvice.java, src/main/java/com/fasttime/domain/comment/dto/request/CommentPageRequestDTO.java, src/main/java/com/fasttime/domain/comment/dto/request/GetCommentsRequestDTO.java, src/main/java/com/fasttime/domain/comment/dto/response/CommentListResponseDTO.java, src/main/java/com/fasttime/domain/comment/entity/Comment.java, src/main/java/com/fasttime/domain/comment/exception/MultipleSearchConditionException.java, src/main/java/com/fasttime/domain/comment/repository/CommentCustomRepository.java, src/main/java/com/fasttime/domain/comment/repository/CommentCustomRepositoryImpl.java, src/main/java/com/fasttime/domain/comment/service/CommentService.java, src/main/java/com/fasttime/global/exception/ErrorCode.java, src/main/resources/application.yaml, src/test/java/com/fasttime/domain/comment/docs/CommentControllerDocsTest.java, src/test/java/com/fasttime/domain/comment/unit/controller/CommentRestControllerTest.java, src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java
- 댓글 페이징 기능 수정
- 댓글 페이징에 Pageable 사용하도록 수정
-  댓글 목록 조회 시 총 페이지 수, 댓글 전체 수, 마지막 페이지 여부 정보 추가 응답
- 댓글 목록 다중 조건 조회 예외 처리 추가
- 댓글 목록 조회 기능의 수정에 따른 테스트 코드 수정
=> 댓글 페이징 기능 수정 및 리팩토링
