fcstudy-project/FastTime-backend

src/main/java/com/fasttime/domain/post/controller/PostController.java, src/main/java/com/fasttime/domain/post/dto/controller/request/PostCreateRequestDto.java, src/main/java/com/fasttime/domain/post/dto/usecase/request/PostCreateServiceDto.java, src/main/java/com/fasttime/domain/post/dto/usecase/response/PostResponseDto.java, src/main/java/com/fasttime/domain/post/entity/Post.java, src/main/java/com/fasttime/domain/post/entity/PostContent.java, src/main/java/com/fasttime/domain/post/repository/PostRepository.java, src/main/java/com/fasttime/domain/post/service/PostService.java, src/test/java/com/fasttime/domain/post/unit/entity/PostTest.java, src/test/java/com/fasttime/domain/post/unit/service/PostServiceTest.java
다른 도메인에서 해당 기능이 필요해 psudo 코드 수준으로 작성했습니다.
Service Layer API 가 불완전하기 때문에 Repository Layer API를 사용해주시면 될 것 같습니다.
* #4
=> 사용자는 게시글을 작성할 수 있다.

src/main/java/com/fasttime/domain/post/entity/Post.java, src/main/java/com/fasttime/domain/post/entity/ReportStatus.java, src/main/java/com/fasttime/domain/post/service/PostService.java, src/test/java/com/fasttime/domain/post/unit/entity/PostTest.java
* 신고 여부를 파악가능한 ReportStatus 추가
* 테스트용 MockObject를 위한 Builder 추가
* 정적 팩토리 메서드의 명칭을 더욱 명확하게 변경
* ISSUE #4
=> 게시글 엔티티 변경

build.gradle, src/main/java/com/fasttime/domain/post/dto/usecase/response/PostResponseDto.java, src/main/java/com/fasttime/domain/post/entity/Post.java, src/test/java/com/fasttime/domain/post/unit/service/PostServiceTest.java, src/test/resources/application.yaml
* h2 의존성 설정
* 테스트 전용 `application.yaml` 설정
* ISSUE #6
=> 테스트 환경을 구축한다.

build.gradle, src/main/java/com/fasttime/domain/member/controller/EmailController.java, src/main/java/com/fasttime/domain/member/controller/MemberController.java, src/main/java/com/fasttime/domain/member/dto/MemberDto.java, src/main/java/com/fasttime/domain/member/entity/Member.java, src/main/java/com/fasttime/domain/member/exception/UserNotFoundException.java, src/main/java/com/fasttime/domain/member/repository/MemberRepository.java, src/main/java/com/fasttime/domain/member/request/DeleteRequest.java, src/main/java/com/fasttime/domain/member/request/EmailRequest.java, src/main/java/com/fasttime/domain/member/service/EmailService.java, src/main/java/com/fasttime/domain/member/service/MemberService.java, src/main/java/com/fasttime/global/config/EmailConfig.java, src/main/resources/application.yaml, src/test/java/com/fasttime/domain/member/controller/EmailControllerTest.java, src/test/java/com/fasttime/domain/member/controller/MemberControllerTest.java
comment 기능 쪽에서 요청한 member repository 업로드 합니다. 
회원가입 기능은 아직 구현 중입니다.
=> comment 기능 구현을 위한 Feature/join 중간 업로드

src/main/java/com/fasttime/domain/post/entity/Post.java, src/main/java/com/fasttime/domain/post/entity/ReportStatus.java, src/main/java/com/fasttime/global/common/BaseTimeEntity.java, src/test/java/com/fasttime/domain/post/unit/entity/PostTest.java
- 게시글 신고 기능추가
- 신고 허용 및 거절 가능
- 삭제 로직 추가
- ReportStatus 변경
- `REPORT_ABORTED` -> `REPORT_REJECTED`
* #22
=> [feature] 게시글 신고를 할 수 있다. #22

src/main/java/com/fasttime/domain/member/controller/MemberControllerAdvice.java, src/main/java/com/fasttime/domain/member/service/MemberService.java, src/test/java/com/fasttime/domain/member/controller/MemberControllerTestForAuto.java
[Fix] Advice관련 오류 수정
[Feat] 의정님이 추가하신 getMember() 메소드 추가
=> [Fix] Advice 재구현

src/main/java/com/fasttime/domain/post/dto/service/request/PostDeleteServiceDto.java, src/main/java/com/fasttime/domain/post/entity/Post.java, src/main/java/com/fasttime/domain/post/service/PostCommandService.java, src/test/java/com/fasttime/domain/post/unit/entity/PostTest.java, src/test/java/com/fasttime/domain/post/unit/service/PostCommandServiceTest.java
* Post Domain 로직 추가
* Post Service 로직 추가
* 테스트 추가
=> 게시글을 삭제할 수 있다.

src/main/java/com/fasttime/domain/member/controller/AdminController.java, src/main/java/com/fasttime/domain/member/controller/EmailController.java, src/main/java/com/fasttime/domain/member/controller/EmailControllerAdvice.java, src/main/java/com/fasttime/domain/member/controller/MemberController.java, src/test/java/com/fasttime/domain/member/controller/AdminControllerTest.java, src/test/java/com/fasttime/domain/member/controller/MemberControllerTestForAuto.java
- restController 기존 url에 api를 추가 
ex) `'/v1/login'` ->` '/api/v1/login' `
- EmailController 코드가 일치하지 않을 때의 예외 구체화
=> [Refactor] url 변경

src/main/java/com/fasttime/domain/post/service/PostCommandService.java, src/main/java/com/fasttime/domain/post/service/PostCommandUseCase.java
Motivation:
- merge 도중 conflict resolve 를 수행하면서 발생한 컴파일 에러를 수정했습니다.
Modification:
- PostResponseDto를 PostResponseDto 로 변환
=> Merge 이후 컴파일 에러 수정

build.gradle
Motivation:
- 이제 Template-Engine이 아닌 Frontend 서버를 따로 운용하기 떄문에 사용하지 않는 thymeleaf 와 같은 dependency를 제거합니다.
Modification:
- 사용하지 않는 dependency를 제거했습니다.
=> [refactor] build.gradle dependency 정리

src/main/java/com/fasttime/domain/member/controller/MemberController.java, src/main/java/com/fasttime/domain/member/response/MemberResponse.java, src/main/java/com/fasttime/domain/member/service/MemberService.java, src/test/java/com/fasttime/domain/member/controller/MemberControllerTestForAuto.java, src/test/java/com/fasttime/domain/member/service/MemberServiceTestForAuto.java
=> login Response 수정

build.gradle, src/main/java/com/fasttime/domain/post/controller/PostController.java, src/main/java/com/fasttime/domain/post/dto/service/response/PostsResponseDto.java, src/main/java/com/fasttime/domain/post/entity/Post.java, src/main/java/com/fasttime/domain/post/entity/PostContent.java, src/main/java/com/fasttime/domain/post/repository/PostRepository.java, src/main/java/com/fasttime/domain/post/repository/PostRepositoryCustom.java, src/main/java/com/fasttime/domain/post/repository/PostRepositoryImpl.java, src/main/java/com/fasttime/domain/post/service/PostQueryService.java, src/main/java/com/fasttime/domain/post/service/PostQueryUseCase.java, src/test/java/com/fasttime/domain/post/repository/PostRepositoryTest.java
Motivation:
- 효율적인 게시글 검색 기능을 추가하기 위해 querydsl을 추가했습니다.
Modification:
- `querydsl` 의존성 추가
- PostRepositoryCustom 추가
- 테스트코드 추가.
=> [feature] 게시글 검색 기능 추가

src/main/java/com/fasttime/global/config/WebConfig.java
=> [fix] WebConfig 수정

src/main/java/com/fasttime/global/interceptor/LoginCheckInterceptor.java, src/test/java/com/fasttime/domain/member/controller/MemberControllerTestForAuto.java
- 인증이 필요한 URL에서 인증 실패 시 ,` redirect URL` ->  `403 Forbidden Error`를 내보내는 것으로 변경
=> [fix] 로그인 인터셉터 수정

src/main/java/com/fasttime/global/config/PasswordEncoderConfig.java
=> [fix] PasswordEncoder 코드 변경

build.gradle, src/docs/asciidoc/index.adoc, src/docs/asciidoc/post/post-api.adoc, src/main/java/com/fasttime/domain/post/controller/PostController.java, src/main/java/com/fasttime/domain/post/dto/controller/request/PostCreateRequestDto.java, src/main/java/com/fasttime/domain/post/dto/controller/request/PostDeleteRequestDto.java, src/main/java/com/fasttime/domain/post/dto/service/request/PostUpdateServiceDto.java, src/main/java/com/fasttime/domain/post/dto/service/response/PostDetailResponseDto.java, src/test/java/com/fasttime/docs/CommonDocsController.java, src/test/java/com/fasttime/docs/CommonDocsTest.java, src/test/java/com/fasttime/docs/RestDocsSupport.java, src/test/java/com/fasttime/domain/post/docs/PostControllerDocsTest.java, src/test/java/com/fasttime/domain/post/unit/repository/PostRepositoryTest.java, src/test/java/com/fasttime/domain/post/unit/service/PostCommandServiceTest.java, src/test/resources/org/springframework/restdocs/templates/request-fields.snippet, src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet, src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Motivation:
- API Spec을 수정하면서 휴먼 에러로 인해 문서와 일치하지 않는 현상이 발생되었습니다.
- 위의 문제를 해결하기 위해서 테스트 기반으로 구동되는 spring rest docs를 사용하기로 결정했습니다. Modification:
Modification: 
- `spring rest docs`, `asciidoctor` 의존성 추가
- 게시글 docs 작성 테스트코드 추가.
- Common docs 작성 테스트코드 추가
=> [feature] spring rest docs 추가

src/main/java/com/fasttime/global/config/SpringSecurityConfig.java, src/main/java/com/fasttime/global/config/WebConfig.java
- 인증 허용 설정 및 모든 헤더 반환 설정 추가
- Security CORS 전체 허용 설정
- CORS origin 와일드카드 사용 시 쿠키 사용이 제한되어 설정 변경
=> [fix] CORS 관련 설정 수정

src/main/java/com/fasttime/domain/post/repository/PostRepositoryCustom.java, src/main/java/com/fasttime/domain/post/repository/PostRepositoryImpl.java, src/main/java/com/fasttime/domain/post/service/PostQueryService.java
Motivation:
- 게시글 조회에서 createdAt, updatedAt이 누락된 것을 수정했습니다.
Modification:
- `createdAt`, `updatedAt` 필드 추가
=> [fix] 게시글 DTO 에 createdAt, updatedAt 필드를 추가한다.

src/main/java/com/fasttime/domain/post/entity/Post.java, src/main/java/com/fasttime/domain/post/service/PostCommandService.java
Motivation:
- 좋아요 싫어요 기능 추가
Modification:
- 좋아요 싫어요 기능 추거
=> [feature] 게시글 좋아요 싫어요 기능 추가

src/main/java/com/fasttime/domain/record/service/RecordService.java, src/test/java/com/fasttime/domain/record/unit/service/RecordServiceTest.java
=> [feat] 게시글 좋아요/싫어요 합계 수정 로직 추가

src/main/java/com/fasttime/domain/member/entity/Member.java, src/main/java/com/fasttime/domain/member/service/MemberService.java
=> [refactor] Member 수정

.gitignore, src/main/java/com/fasttime/domain/member/service/EmailService.java, src/main/java/com/fasttime/global/config/EmailConfig.java, src/main/resources/application.yaml, src/test/java/com/fasttime/util/FakeEmailConfig.java, src/test/resources/application.yaml
Motivation:
- disable 했던 이메일 기능을 enable 했습니다.
Modification:
- 이메일 전송 기능 enable
- username, password 전용 yaml 추가 (.gitignore 된 상태)
=> [feature] 이메일 전송 enable

src/main/java/com/fasttime/domain/comment/entity/Comment.java, src/main/java/com/fasttime/domain/comment/service/CommentService.java, src/test/java/com/fasttime/domain/comment/unit/entity/CommentTest.java
=> [fix] 댓글 삭제 기능 수정

src/main/java/com/fasttime/domain/post/service/PostCommandService.java
Motivation:
- anonymity를 항상 false로 반환하게끔 설정되어 있던 것을 수정했습니다.
Modification:
- `PostCommandService.class` 에서 anonymity 필드 반영하게끔 수정.
=> [fix] anonymity 수정

src/main/java/com/fasttime/domain/comment/controller/CommentRestController.java
- 댓글 삭제 불가
- 서비스단 호출 코드 부재
- 호출 코드 추가
=> [fix] 댓글 삭제 수정

src/main/java/com/fasttime/domain/report/contoller/ReportRestController.java, src/main/java/com/fasttime/domain/report/contoller/ReportRestControllerAdvice.java, src/main/java/com/fasttime/domain/report/dto/request/CreateReportRequestDTO.java, src/main/java/com/fasttime/domain/report/entity/Report.java, src/main/java/com/fasttime/domain/report/exception/AlreadyDeletedPostException.java, src/main/java/com/fasttime/domain/report/exception/DuplicateReportException.java, src/main/java/com/fasttime/domain/report/service/ReportService.java, src/test/java/com/fasttime/domain/report/docs/ReportControllerDocsTest.java, src/test/java/com/fasttime/domain/report/unit/controller/ReportRestControllerTest.java, src/test/java/com/fasttime/domain/report/unit/service/ReportServiceTest.java
- 댓글 API 수정
- 좋아요/싫어요 등록, 조회, 삭제 시 memberId를 필드가 아닌 세션에서 가져옴
- 신고 등록 API url 수정
- 신고 등록 시 신고 DTO를 응답하지 않도록 수정
- FE 에서 필요하지 않다고 하셨음
- 신고 익셉션 메세지 설정 
- 신고 Service, Controller 리팩토링
- 신고 테스트 코드 수정
=> [refactor] 신고 기능 리팩토링

.gitignore, build.gradle, src/main/resources/logback/appender/logback-console.xml, src/main/resources/logback/appender/logback-dev.xml, src/main/resources/logback/appender/logback-local.xml, src/main/resources/logback/appender/logback-prod.xml, src/main/resources/logback/logback-spring.xml
Motivation:
- 라이브 서버에 대한 로그 정보가 충분하지 않아 Logback를 추가했습니다.
- 라이브 서버에서 에러가 난 경우 Discord Webhook을 통해 에러를 보내도록 설정했습니다.
Modification:
- `Logback` 기능 추가.
- `Discord webhook` 추가
=> [feat] Logback 추가

src/main/java/com/fasttime/domain/comment/service/CommentService.java, src/main/java/com/fasttime/domain/member/controller/AdminController.java, src/main/java/com/fasttime/domain/member/service/AdminService.java, src/main/java/com/fasttime/domain/post/repository/PostRepository.java, src/test/java/com/fasttime/domain/comment/unit/service/CommentServiceTest.java, src/test/java/com/fasttime/domain/member/docs/AdminControllerDocsTest.java, src/test/java/com/fasttime/domain/member/unit/service/AdminServiceTest.java
Motivation:
- Merge 중 발생한 컴파일 에러를 수정했습니다.
Modification:
- `findPostById` -> `getPostById`.
- 신고 게시글 조회 페이지네이션 추가
=> [fix] 컴파일 에러 수정

src/main/java/com/fasttime/global/common/BaseTimeEntity.java
Motivation:
- Table의 데이터를 수정해도 수정 일시가 추가되지 않는 상황이 발생되었습니다. 이를 수정하였습니다.
Modification:
- `@LastModifiedDate` 추가
=> [fix] Table의 lastModifiedDate 누락 수정

src/docs/asciidoc/admin/admin-api.adoc, src/test/java/com/fasttime/domain/member/docs/AdminControllerDocsTest.java
=> [feat] Admin 회원가입 Docs 추가

src/main/java/com/fasttime/global/interceptor/LoginCheckInterceptor.java
Motivation:
- NPE 문제 발생을 해결했습니다.
Modification:
- Null Checking 로직 분기처리
=> [fix] LoginCheckInterceptor.java NPE 수정

src/main/java/com/fasttime/domain/member/controller/EmailController.java, src/main/java/com/fasttime/domain/member/controller/MemberController.java, src/test/java/com/fasttime/domain/member/controller/EmailControllerTest.java
- fc_member의 이메일인지 확인하는 기능을 join에서 emailconfirm으로 옮겼습니다.
- emailcontroller test코드를 수정했습니다.
-------
- 그 외의 코드 리펙토링 진행 중입니다.
=> [fix] fc_member확인 기능을 email에 적용한다.

src/main/java/com/fasttime/global/config/WebConfig.java
Motivation:
- frontend 측에서 도메인 주소를 등록했기 때문에 해당 도메인 주소를 등록했습니다.
Modification:
- front 도메인 주소로 변경
=> [fix] cors origin pattern 등록
